administration_dashboard:
    pattern: /admin
    defaults: { _controller: "GitonomyWebsiteBundle:Administration:dashboard" }

administration_users:
    pattern: /admin/users
    defaults: { _controller: "GitonomyWebsiteBundle:Administration:users" }

administration_roles:
    pattern: /admin/roles
    defaults: { _controller: "GitonomyWebsiteBundle:Administration:roles" }
