# Gitonomy core
gitonomy_core:
    repository_path:   %repository_path%
    async_storage:     direct

twig:
    form:
        resources: [ "GitonomyWebsiteBundle::form.html.twig" ]
    globals:
        gitonomy:
            name:       %project_name%
            baseline:   %project_baseline%
            ssh_access: %ssh_access%
