# Gitonomy core
gitonomy_core:
    repository_path:   %repository_path%

gitonomy_frontend:
    project_name:      %project_name%
    project_baseline:  %project_baseline%
    open_registration: %open_registration%
    ssh_access:        %ssh_access%
    allowed_locales:   [ fr_FR, en_US ]
    mailer:
        from:          %mail_from%
        to:            %mail_to%

twig:
    form:
        resources: [ "GitonomyFrontendBundle::form.html.twig" ]
