# Gitonomy core
gitonomy_core:
    repository_path:   %repository_path%

gitonomy_frontend:
    project_name:      %project_name%
    open_registration: %open_registration%
    ssh_access:        %ssh_access%
    allowed_locales:   [ fr_FR, en_US ]

twig:
    form:
        resources: [ "GitonomyFrontendBundle::form.html.twig" ]
