_gitonomy_frontend:
    resource: "@GitonomyFrontendBundle/Resources/config/routing.yml"

_gitonomy_website:
    resource: "@GitonomyWebsiteBundle/Resources/config/routing.yml"
    prefix: /{_locale}/v2


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
