_gitonomy_frontend:
    resource: "@GitonomyFrontendBundle/Resources/config/routing.yml"
    prefix: /{_locale}

gitonomyfrontend_main_noLocaleHomepage:
    pattern: /
    defaults: { _controller: "GitonomyFrontendBundle:Main:homepage" }


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
