security:
    encoders:
        Gitonomy\Bundle\CoreBundle\Entity\User:
            algorithm:        sha512
            encode-as-base64: true
            iterations:       5

    providers:
        entity:
            entity: { class: "Gitonomy\Bundle\CoreBundle\Entity\User", property: "username" }

    firewalls:
        main:
            pattern:    "/.*"
            security:   true
            form_login: true
            logout:     true
            anonymous:  true
