gitonomyfrontend_adminproject_list:
    pattern: /adminproject/list
    defaults: { _controller: "GitonomyFrontendBundle:AdminProject:list" }

gitonomyfrontend_adminproject_create:
    pattern: /adminproject/create
    defaults: { _controller: "GitonomyFrontendBundle:AdminProject:create" }

gitonomyfrontend_adminproject_edit:
    pattern: /adminproject/{id}/edit
    defaults: { _controller: "GitonomyFrontendBundle:AdminProject:edit" }
    requirements:
        id:  \d+

gitonomyfrontend_adminproject_delete:
    pattern: /adminproject/{id}/delete
    defaults: { _controller: "GitonomyFrontendBundle:AdminProject:delete" }
    requirements:
        id:  \d+
