gitonomyfrontend_adminuser_list:
    pattern: /{_locale}/adminuser/list
    defaults: { _controller: "GitonomyFrontendBundle:AdminUser:list" }

gitonomyfrontend_adminuser_create:
    pattern: /{_locale}/adminuser/create
    defaults: { _controller: "GitonomyFrontendBundle:AdminUser:create" }

gitonomyfrontend_adminuser_edit:
    pattern: /{_locale}/adminuser/{id}/edit
    defaults: { _controller: "GitonomyFrontendBundle:AdminUser:edit" }
    requirements:
        id:  \d+

gitonomyfrontend_adminuser_delete:
    pattern: /{_locale}/adminuser/{id}/delete
    defaults: { _controller: "GitonomyFrontendBundle:AdminUser:delete" }
    requirements:
        id:  \d+

gitonomyfrontend_adminuser_projectroles:
    pattern: /{_locale}/adminuser/{userId}/userrole
    defaults: { _controller: "GitonomyFrontendBundle:AdminUser:userRoles" }
    requirements:
        userId:  \d+

gitonomyfrontend_adminuser_projectroles_delete:
    pattern: /{_locale}/adminuser/projectrole/{id}/delete
    defaults: { _controller: "GitonomyFrontendBundle:AdminUser:deleteUserRole" }
    requirements:
        id:  \d+

gitonomyfrontend_adminuser_emails:
    pattern: /{_locale}/adminuser/{userId}/emails
    defaults: { _controller: "GitonomyFrontendBundle:AdminUser:emails" }
    requirements:
        userId:  \d+

gitonomyfrontend_adminuser_email_delete:
    pattern: /{_locale}/adminuser/email/{id}/delete
    defaults: { _controller: "GitonomyFrontendBundle:AdminUser:deleteEmail" }
    requirements:
        id:  \d+
