gitonomyfrontend_adminproject_list:
    pattern: /{_locale}/adminproject/list
    defaults: { _controller: "GitonomyFrontendBundle:AdminProject:list" }

gitonomyfrontend_adminproject_create:
    pattern: /{_locale}/adminproject/create
    defaults: { _controller: "GitonomyFrontendBundle:AdminProject:create" }

gitonomyfrontend_adminproject_edit:
    pattern: /{_locale}/adminproject/{id}/edit
    defaults: { _controller: "GitonomyFrontendBundle:AdminProject:edit" }

gitonomyfrontend_adminproject_delete:
    pattern: /{_locale}/adminproject/{id}/delete
    defaults: { _controller: "GitonomyFrontendBundle:AdminProject:delete" }

gitonomyfrontend_adminproject_gitAccesses:
    pattern: /{_locale}/adminproject/{id}/git-accesses
    defaults: { _controller: "GitonomyFrontendBundle:AdminProject:gitAccesses" }

gitonomyfrontend_adminproject_gitAccessDelete:
    pattern: /{_locale}/adminproject/git-accesses/{gitAccessId}/delete
    defaults: { _controller: "GitonomyFrontendBundle:AdminProject:gitAccessDelete" }

gitonomyfrontend_adminproject_userRoles:
    pattern: /{_locale}/adminproject/{id}/user-roles
    defaults: { _controller: "GitonomyFrontendBundle:AdminProject:userRoles" }

gitonomyfrontend_adminproject_userRoleDelete:
    pattern: /{_locale}/adminproject/user-roles/{userRoleId}/delete
    defaults: { _controller: "GitonomyFrontendBundle:AdminProject:userRoleDelete" }
