gitonomyfrontend_main_homepage:
    pattern: /
    defaults: { _controller: "GitonomyFrontendBundle:Main:homepage" }

gitonomyfrontend_main_setLocale:
    pattern: /but-i-would-prefer-{locale}
    defaults: { _controller: "GitonomyFrontendBundle:Main:setLocale" }
