gitonomyfrontend_main_noLocaleHomepage:
    pattern: /
    defaults: { _controller: "GitonomyFrontendBundle:Main:homepage" }

gitonomyfrontend_main_homepage:
    pattern: /{_locale}
    defaults: { _controller: "GitonomyFrontendBundle:Main:homepage" }

gitonomyfrontend_main_setLocale:
    pattern: /{_locale}/but-i-would-prefer-{locale}
    defaults: { _controller: "GitonomyFrontendBundle:Main:setLocale" }
