gitonomyfrontend_profile_index:
    pattern: /profile
    defaults: { _controller: "GitonomyFrontendBundle:Profile:index" }

gitonomyfrontend_profile_sshKeys:
    pattern: /profile/ssh-keys
    defaults: { _controller: "GitonomyFrontendBundle:Profile:sshKeys" }

gitonomyfrontend_profile_deleteSshKey:
    pattern: /profile/delete-ssh-key/{id}
    defaults: { _controller: "GitonomyFrontendBundle:Profile:deleteSshKey" }

gitonomyfrontend_profile_createSshKey:
    pattern: /profile/create-ssh-key
    defaults: { _controller: "GitonomyFrontendBundle:Profile:createSshKey" }
