gitonomyfrontend_profile_index:
    pattern: /{_locale}/profile
    defaults: { _controller: "GitonomyFrontendBundle:Profile:index" }

gitonomyfrontend_profile_sshKeys:
    pattern: /{_locale}/profile/ssh-keys
    defaults: { _controller: "GitonomyFrontendBundle:Profile:sshKeys" }

gitonomyfrontend_profile_emails:
    pattern: /{_locale}/profile/emails
    defaults: { _controller: "GitonomyFrontendBundle:Profile:emails" }

gitonomyfrontend_profile_deleteSshKey:
    pattern: /{_locale}/profile/delete-ssh-key/{id}
    defaults: { _controller: "GitonomyFrontendBundle:Profile:deleteSshKey" }

gitonomyfrontend_profile_createSshKey:
    pattern: /{_locale}/profile/create-ssh-key
    defaults: { _controller: "GitonomyFrontendBundle:Profile:createSshKey" }

gitonomyfrontend_profile_changeUsername:
    pattern: /{_locale}/profile/change-username
    defaults: { _controller: "GitonomyFrontendBundle:Profile:changeUsername" }

gitonomyfrontend_profile_activate:
    pattern: /{_locale}/profile/{username}/activate/{token}
    defaults: { _controller: "GitonomyFrontendBundle:Profile:activate" }
    requirements:
        id:   \d+
        hash: \w+
