gitonomyfrontend_project_show:
    pattern: /{_locale}/project/{slug}
    defaults: { _controller: "GitonomyFrontendBundle:Project:show" }
    requirements: { reference: ".*" }

gitonomyfrontend_project_showLastCommits:
    pattern: /{_locale}/project/{slug}/commits/{reference}
    defaults: { _controller: "GitonomyFrontendBundle:Project:showLastCommits" }

gitonomyfrontend_project_showCommit:
    pattern: /{_locale}/project/{slug}/view-commit/{hash}
    defaults: { _controller: "GitonomyFrontendBundle:Project:showCommit" }

gitonomyfrontend_project_showGraph:
    pattern: /{_locale}/project/{slug}/graph
    defaults: { _controller: "GitonomyFrontendBundle:Project:showGraph" }
