gitonomyfrontend_repository_show:
    pattern: /{_locale}/__/{namespace}/{name}
    defaults: { _controller: "GitonomyFrontendBundle:Repository:show" }

gitonomyfrontend_repository_fork:
    pattern: /{_locale}/__/{namespace}/{name}/fork
    defaults: { _controller: "GitonomyFrontendBundle:Repository:fork" }
