gitonomyfrontend_role_list:
    pattern: /role/list
    defaults: { _controller: "GitonomyFrontendBundle:Role:list" }

gitonomyfrontend_role_create:
    pattern: /role/create
    defaults: { _controller: "GitonomyFrontendBundle:Role:create" }

gitonomyfrontend_role_edit:
    pattern: /role/{id}/edit
    defaults: { _controller: "GitonomyFrontendBundle:Role:edit" }
    requirements:
        id:  \d+

gitonomyfrontend_role_delete:
    pattern: /role/{id}/delete
    defaults: { _controller: "GitonomyFrontendBundle:Role:delete" }
    requirements:
        id:  \d+
