gitonomyfrontend_security_login:
    pattern: /{_locale}/login
    defaults: { _controller: "GitonomyFrontendBundle:Security:login" }

gitonomyfrontend_security_loginCheck:
    pattern: /{_locale}/login_check
    defaults: { _controller: "GitonomyFrontendBundle:Security:loginCheck" }

gitonomyfrontend_security_logout:
    pattern: /{_locale}/logout
    defaults: { _controller: "GitonomyFrontendBundle:Security:logout" }

gitonomyfrontend_security_forgotPassword:
    pattern: /{_locale}/password
    defaults: { _controller: "GitonomyFrontendBundle:Security:forgotPassword" }

gitonomyfrontend_security_changePassword:
    pattern: /{_locale}/password/{username}/{forgotPasswordToken}
    defaults: { _controller: "GitonomyFrontendBundle:Security:changePassword" }
