gitonomyfrontend_security_login:
    pattern: /{_locale}/login
    defaults: { _controller: "GitonomyFrontendBundle:Security:login" }

gitonomyfrontend_security_loginCheck:
    pattern: /{_locale}/login_check
    defaults: { _controller: "GitonomyFrontendBundle:Security:loginCheck" }

gitonomyfrontend_security_logout:
    pattern: /{_locale}/logout
    defaults: { _controller: "GitonomyFrontendBundle:Security:logout" }
