_splash:
    resource: "@GitonomyWebsiteBundle/Resources/config/routing/splash.yml"

_project:
    resource: "@GitonomyWebsiteBundle/Resources/config/routing/project.yml"

_user:
    resource: "@GitonomyWebsiteBundle/Resources/config/routing/user.yml"

administration_dashboard:
    pattern: /admin
    defaults: { _controller: "GitonomyWebsiteBundle:Administration:dashboard" }

administration_users:
    pattern: /admin/users
    defaults: { _controller: "GitonomyWebsiteBundle:Administration:users" }

administration_roles:
    pattern: /admin/roles
    defaults: { _controller: "GitonomyWebsiteBundle:Administration:roles" }

preferences_informations:
    pattern: /preferences
    defaults: { _controller: "GitonomyWebsiteBundle:Preferences:informations" }

preferences_sshKeys:
    pattern: /preferences/ssh-keys
    defaults: { _controller: "GitonomyWebsiteBundle:Preferences:sshKeys" }
