_gitonomyfrontend_main:
    resource: routing/main.yml

_gitonomyfrontend_security:
    resource: routing/security.yml

_gitonomyfrontend_user:
    resource: routing/user.yml

_gitonomyfrontend_role:
    resource: routing/role.yml

_gitonomyfrontend_profile:
    resource: routing/profile.yml

_gitonomyfrontend_repository:
    resource: routing/repository.yml
