_gitonomyfrontend_main:
    resource: routing/main.yml

_gitonomyfrontend_security:
    resource: routing/security.yml

_gitonomyfrontend_adminrole:
    resource: routing/adminrole.yml

_gitonomyfrontend_adminproject:
    resource: routing/adminproject.yml

_gitonomyfrontend_adminuser:
    resource: routing/adminuser.yml

_gitonomyfrontend_profile:
    resource: routing/profile.yml

_gitonomyfrontend_email:
    resource: routing/email.yml

_gitonomyfrontend_project:
    resource: routing/project.yml

_gitonomyfrontend_user:
    resource: routing/user.yml
